In [26]:
import numpy as np
import torch
import nltk
from nltk.cluster.kmeans import KMeansClusterer

feature_dim = 128
batch_size = 256

ov = np.random.rand(batch_size,feature_dim)
print(ov.shape)
av = np.random.rand(batch_size,feature_dim)

k = 10
            #from spherecluster import SphericalKMeans
clusterer = KMeansClusterer(k, distance=nltk.cluster.util.cosine_distance, repeats=20, normalise=True, avoid_empty_clusters=True)
            #skm = SphericalKMeans(n_clusters=k)
            #skm.fit(ov)
clusterer_I = KMeansClusterer(k, distance=nltk.cluster.util.cosine_distance, repeats=20, normalise=True, avoid_empty_clusters=True)
labels_ = clusterer.cluster(ov,True)
labels_I = clusterer_I.cluster(av,True)
cluster_centers = torch.Tensor( np.array(clusterer.means()) ) 
cluster_centers_I = torch.Tensor( np.array(clusterer_I.means()) )

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.o

(256, 128)


In [31]:
center = [ cluster_centers[i] for i in range(k) ]
center_I = [ cluster_centers_I[i] for i in range(k) ]
center

[tensor([0.0667, 0.0829, 0.0696, 0.0720, 0.0767, 0.0834, 0.0648, 0.0747, 0.0725,
         0.0807, 0.0786, 0.0948, 0.0924, 0.0857, 0.0827, 0.0705, 0.0586, 0.0790,
         0.0801, 0.0871, 0.0618, 0.0734, 0.0699, 0.0720, 0.0753, 0.0879, 0.0687,
         0.0665, 0.0813, 0.0714, 0.0782, 0.0767, 0.0640, 0.0833, 0.0721, 0.0695,
         0.0742, 0.1079, 0.0606, 0.0814, 0.0681, 0.0847, 0.0862, 0.0509, 0.0742,
         0.0717, 0.0637, 0.0732, 0.0590, 0.0608, 0.0748, 0.0799, 0.0758, 0.1049,
         0.0841, 0.0818, 0.0732, 0.0776, 0.0888, 0.0844, 0.0690, 0.0733, 0.0708,
         0.0934, 0.0916, 0.0962, 0.0788, 0.0635, 0.0864, 0.0601, 0.0656, 0.0698,
         0.0903, 0.0694, 0.0570, 0.0779, 0.0977, 0.0864, 0.0929, 0.0916, 0.1014,
         0.0710, 0.0602, 0.0690, 0.0857, 0.0534, 0.0908, 0.0690, 0.0621, 0.0684,
         0.0832, 0.0589, 0.0763, 0.0790, 0.0898, 0.0860, 0.0710, 0.0851, 0.0786,
         0.0602, 0.0731, 0.0951, 0.0953, 0.0603, 0.0701, 0.0643, 0.0652, 0.0713,
         0.0857, 0.0700, 0.0

In [32]:
cdat = [ x.unsqueeze(0).expand(batch_size,feature_dim) for x in center]
cdat[0].shape

torch.Size([256, 128])

In [34]:
test = torch.stack([cluster_centers,cluster_centers_I],dim=0)
test.shape

#len(labels_[1:])

torch.Size([2, 10, 128])

In [26]:
tt = torch.zeros([256,128])
tt

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [9]:
mask = np.zeros([256])
mask[3] = 1
mask[89] = 1
mask[123] = 1
mask[12] = 1
mask

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [12]:

test = np.zeros([256,128])
for j in range(256): test[j] = ov[j,:]*mask[j]
    
test


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
full = torch.Tensor(test.sum(axis=0))
full

tensor([1.8004, 1.0218, 2.2712, 1.5216, 1.5911, 2.1567, 2.1957, 1.4778, 0.9642,
        2.2141, 1.2309, 1.4722, 2.3654, 2.1464, 1.3858, 1.9947, 2.3275, 2.1586,
        2.2215, 2.0483, 2.0320, 2.7343, 1.8062, 1.9067, 2.0160, 1.2219, 1.4781,
        0.8772, 2.6941, 1.0765, 1.2240, 1.6048, 1.2305, 2.4377, 2.5193, 1.7954,
        1.8876, 1.4313, 2.9403, 2.7630, 1.5044, 1.5977, 1.4117, 1.3609, 0.9260,
        1.2488, 2.6444, 2.4981, 2.0521, 2.1192, 2.7553, 2.9904, 2.6347, 2.0229,
        2.2887, 1.4492, 2.7866, 1.9758, 1.1116, 2.9795, 1.5936, 2.2372, 1.0480,
        1.7525, 1.8079, 1.8480, 2.2686, 2.4383, 2.6425, 2.4132, 0.8812, 2.8395,
        1.7283, 2.2502, 2.6496, 2.3787, 1.2434, 1.0884, 2.6112, 1.7283, 2.5096,
        2.7801, 2.3378, 1.4065, 2.9754, 2.2778, 1.4525, 1.7534, 1.7089, 1.8786,
        1.2815, 1.2808, 1.7761, 1.7805, 1.6126, 2.1700, 2.9951, 1.3185, 2.6919,
        2.0858, 1.3892, 1.1936, 3.1327, 1.1422, 2.1617, 2.6481, 1.3488, 2.2236,
        1.2288, 1.4163, 1.3945, 1.4094, 

In [22]:
rt = torch.stack([full,full])
rt.shape

torch.Size([2, 128])

In [23]:
result = torch.nn.functional.normalize(rt)
result

tensor([[0.0797, 0.0452, 0.1006, 0.0674, 0.0705, 0.0955, 0.0972, 0.0654, 0.0427,
         0.0980, 0.0545, 0.0652, 0.1047, 0.0950, 0.0614, 0.0883, 0.1031, 0.0956,
         0.0984, 0.0907, 0.0900, 0.1211, 0.0800, 0.0844, 0.0893, 0.0541, 0.0655,
         0.0388, 0.1193, 0.0477, 0.0542, 0.0711, 0.0545, 0.1079, 0.1116, 0.0795,
         0.0836, 0.0634, 0.1302, 0.1224, 0.0666, 0.0707, 0.0625, 0.0603, 0.0410,
         0.0553, 0.1171, 0.1106, 0.0909, 0.0938, 0.1220, 0.1324, 0.1167, 0.0896,
         0.1013, 0.0642, 0.1234, 0.0875, 0.0492, 0.1319, 0.0706, 0.0991, 0.0464,
         0.0776, 0.0801, 0.0818, 0.1005, 0.1080, 0.1170, 0.1069, 0.0390, 0.1257,
         0.0765, 0.0996, 0.1173, 0.1053, 0.0551, 0.0482, 0.1156, 0.0765, 0.1111,
         0.1231, 0.1035, 0.0623, 0.1318, 0.1009, 0.0643, 0.0776, 0.0757, 0.0832,
         0.0567, 0.0567, 0.0786, 0.0788, 0.0714, 0.0961, 0.1326, 0.0584, 0.1192,
         0.0924, 0.0615, 0.0529, 0.1387, 0.0506, 0.0957, 0.1173, 0.0597, 0.0985,
         0.0544, 0.0627, 0.0

In [25]:
torch.nn.functional.normalize(rt,dim=0)

tensor([[0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071, 0.7071,
         0.7071, 0.7071, 0.7

In [15]:
import torch

im2cluster = torch.LongTensor([0,1,2,9,4,5,6,7,8,9])
indices = torch.Tensor([3,5,8,5])
result = torch.zeros(indices.shape)
#result = im2cluster[torch.LongTensor(indices)]

result

tensor([0., 0., 0., 0.])

In [16]:
for i in range(len(result)): result[i] = im2cluster[int(indices[i])]
result

tensor([9., 5., 8., 5.])

In [14]:
mask = (result == 5).type(torch.LongTensor)
mask

tensor([0, 1, 0])

In [11]:
result[mask]

tensor([5.])

In [18]:
mask = result == 5
idx = torch.rand([4,128])
res = idx[mask]
res

tensor([[0.4458, 0.4328, 0.4932, 0.0688, 0.6126, 0.3331, 0.6807, 0.0957, 0.7779,
         0.4042, 0.4741, 0.9223, 0.3594, 0.4110, 0.2852, 0.4154, 0.6166, 0.4803,
         0.5927, 0.4580, 0.1069, 0.5968, 0.5103, 0.5048, 0.7451, 0.9386, 0.9667,
         0.0124, 0.3030, 0.3234, 0.2924, 0.9119, 0.5590, 0.8090, 0.8660, 0.2469,
         0.6935, 0.9911, 0.7713, 0.8186, 0.4629, 0.0597, 0.5654, 0.7187, 0.7101,
         0.7079, 0.0769, 0.0592, 0.2426, 0.0717, 0.8110, 0.7377, 0.0772, 0.2047,
         0.2644, 0.7810, 0.0666, 0.7645, 0.3487, 0.5125, 0.3880, 0.5742, 0.3107,
         0.6402, 0.1851, 0.8702, 0.8876, 0.5102, 0.6056, 0.3790, 0.6425, 0.0056,
         0.5760, 0.3056, 0.7507, 0.5562, 0.2750, 0.5403, 0.8071, 0.8797, 0.3374,
         0.9388, 0.4720, 0.9550, 0.0600, 0.5554, 0.8450, 0.6971, 0.9577, 0.9036,
         0.8057, 0.2719, 0.7022, 0.8459, 0.5952, 0.3173, 0.3310, 0.6273, 0.0081,
         0.9530, 0.0851, 0.7687, 0.1682, 0.2168, 0.1417, 0.2472, 0.8524, 0.1160,
         0.4256, 0.4162, 0.4

In [24]:
zz = torch.sum(res,dim=0)
zz.shape

torch.Size([128])

In [25]:
zz/2

tensor([0.6493, 0.6382, 0.2575, 0.3286, 0.7348, 0.2993, 0.6396, 0.1503, 0.5341,
        0.5127, 0.6892, 0.7667, 0.6624, 0.2132, 0.4122, 0.3713, 0.4488, 0.5578,
        0.3437, 0.6160, 0.2226, 0.5003, 0.5528, 0.3922, 0.4841, 0.5999, 0.8027,
        0.4304, 0.2538, 0.3401, 0.3875, 0.5960, 0.3603, 0.5835, 0.5363, 0.2271,
        0.5775, 0.9510, 0.5335, 0.6852, 0.4261, 0.1217, 0.3329, 0.4092, 0.5523,
        0.6596, 0.4410, 0.2943, 0.5384, 0.1718, 0.5212, 0.8100, 0.1561, 0.4306,
        0.4940, 0.6403, 0.3231, 0.7056, 0.3824, 0.5834, 0.2250, 0.6639, 0.6476,
        0.5029, 0.5685, 0.7885, 0.6583, 0.6479, 0.6086, 0.4948, 0.3811, 0.0197,
        0.6769, 0.3969, 0.4626, 0.5832, 0.5886, 0.3967, 0.6963, 0.4766, 0.3545,
        0.6742, 0.3063, 0.5454, 0.4034, 0.5384, 0.4520, 0.5934, 0.6756, 0.6636,
        0.5590, 0.3677, 0.7638, 0.4985, 0.7317, 0.5528, 0.3545, 0.5216, 0.1069,
        0.8173, 0.2399, 0.7623, 0.5055, 0.5550, 0.2404, 0.6020, 0.4659, 0.4397,
        0.3960, 0.3083, 0.6725, 0.0688, 